🚨 [web] Revert turbo from 2.0.1 to 1.13.4 due to Vercel deployment issues
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.